FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm ci 

ENV NODE_ENV=production

COPY . .

RUN npm run build

FROM nginx:1.25.3-alpine as production

ENV NODE_ENV=production

ENV VITE_BASE_URL=/

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]